// Generated by scripts/audio/build_music.py: do not edit.
import theme from '../../assets/audio/music_theme.mp3';

/** The Night Express theme: one pass plus the tail of its last bar; passes start `loopSeconds` apart. */
export const MUSIC = { data: theme, loopSeconds: 48 };
